version: '3'

services:
  soa.assignment.mooc:
    image: soa.assignment.mooc
    build:
      context: ./SOA.Assignment.Mooc
      dockerfile: Dockerfile
    ports:
      - 8082:80
  swagger.ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      - API_URL=http://localhost:8082/swagger/v1/swagger.json
